13:58:20 | Error | Erro inesperado na aplicação | ::1 | Controller: Authentication | Action: Login | Unable to resolve service for type 'PedidoAPI.Services.TokenService' while attempting to activate 'PedidoAPI.Controllers.AuthenticationController'.
13:58:34 | Error | Erro inesperado na aplicação | ::1 | Controller: Authentication | Action: Login | Unable to resolve service for type 'PedidoAPI.Services.TokenService' while attempting to activate 'PedidoAPI.Controllers.AuthenticationController'.
14:31:02 | Error | Erro inesperado na aplicação | ::1 | Controller: Usuarios | Action: GetUsuarioById | StatusCode cannot be set because the response has already started.
14:31:02 | Error | An unhandled exception has occurred while executing the request. | StatusCode cannot be set because the response has already started.
14:31:02 | Error | Connection id "0HNAKV3U5HPUM", Request id "0HNAKV3U5HPUM:00000009": An unhandled exception was thrown by the application. | StatusCode cannot be set because the response has already started.
14:32:03 | Error | Erro inesperado na aplicação | ::1 | Controller: Usuarios | Action: GetUsuarioById | StatusCode cannot be set because the response has already started.
14:32:03 | Error | An unhandled exception has occurred while executing the request. | StatusCode cannot be set because the response has already started.
14:32:03 | Error | Connection id "0HNAKV3U5HPUM", Request id "0HNAKV3U5HPUM:0000000B": An unhandled exception was thrown by the application. | StatusCode cannot be set because the response has already started.
14:38:11 | Error | Erro inesperado na aplicação | ::1 | Controller: Authentication | Action: Login | StatusCode cannot be set because the response has already started.
14:38:11 | Error | An unhandled exception has occurred while executing the request. | StatusCode cannot be set because the response has already started.
14:38:11 | Error | Connection id "0HNAKV7CLU361", Request id "0HNAKV7CLU361:0000000B": An unhandled exception was thrown by the application. | StatusCode cannot be set because the response has already started.
14:38:42 | Error | Erro inesperado na aplicação | ::1 | Controller: Authentication | Action: Login | StatusCode cannot be set because the response has already started.
14:38:42 | Error | An unhandled exception has occurred while executing the request. | StatusCode cannot be set because the response has already started.
14:38:42 | Error | Connection id "0HNAKV7CLU361", Request id "0HNAKV7CLU361:0000000D": An unhandled exception was thrown by the application. | StatusCode cannot be set because the response has already started.
14:41:29 | Error | Erro inesperado na aplicação | ::1 | Controller: Usuarios | Action: GetUsuarioById | StatusCode cannot be set because the response has already started.
14:41:29 | Error | An unhandled exception has occurred while executing the request. | StatusCode cannot be set because the response has already started.
14:41:29 | Error | Connection id "0HNAKV8QP9GUS", Request id "0HNAKV8QP9GUS:00000017": An unhandled exception was thrown by the application. | StatusCode cannot be set because the response has already started.
21:09:31 | Error | Erro ao executar consulta. SQL: select * from Pedido where usuarioid = 15 order by Id offset 0 rows fetch next @pagesize rows only | The message timed out in the backlog attempting to send because no connection became available (5000ms) - Last Connection Exception: UnableToConnect on 172.27.51.24:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.8.24.3255, command=HMGET, timeout: 5000, inst: 0, qu: 0, qs: 0, aw: False, bw: CheckingForTimeout, rs: NotStarted, ws: Idle, in: 0, last-in: 0, cur-in: 0, sync-ops: 0, async-ops: 1, serverEndpoint: 172.27.51.24:6379, conn-sec: n/a, aoc: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: LEANDRO(SE.Redis-v2.8.24.3255), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=0,Free=32767,Min=8,Max=32767), POOL: (Threads=7,QueuedItems=0,CompletedItems=396,Timers=8), v: 2.8.24.3255 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
22:45:53 | Error | Erro ao executar consulta. SQL: select * from Pedido where usuarioid = 16 order by Id offset 0 rows fetch next @pagesize rows only | The message timed out in the backlog attempting to send because no connection became available (5000ms) - Last Connection Exception: It was not possible to connect to the redis server(s). ConnectTimeout, command=EVAL, timeout: 5000, inst: 0, qu: 0, qs: 0, aw: False, bw: CheckingForTimeout, rs: NotStarted, ws: Initializing, last-in: 0, cur-in: 0, sync-ops: 0, async-ops: 2, serverEndpoint: 172.27.51.24:6379, conn-sec: n/a, aoc: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: LEANDRO(SE.Redis-v2.8.24.3255), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=8,Max=32767), POOL: (Threads=7,QueuedItems=0,CompletedItems=441,Timers=7), v: 2.8.24.3255 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
